### ISSUE TITLE
Corrigir componente "Button.vue"

### ISSUE THREAD

**Issue by daniel-francelino** [daniel-soaress/vplayer#14]
- Como está:
![Image](https://github.com/daniel-soaress/vplayer/assets/27651005/1031a76f-ab60-4e42-bdf3-8b259823e9bc)

- Como deve ser:
![Image](https://github.com/daniel-soaress/vplayer/assets/27651005/4dbd5cbb-775a-42a6-a175-fe622b059b28)

**Comment by Isaacvf-dev** [comment]
https://vuejs.org/guide/typescript/composition-api.html#typing-event-handlers
