### ISSUE TITLE
Setup project

### ISSUE THREAD

**Issue by daniel-francelino** [daniel-soaress/vplayer#15]
- [x]  Clonar [projeto](https://github.com/daniel-soaress/vplayer): (git clone); 
- [x]  Instalar na [Node](https://nodejs.org/en), versão LTS.
- [x]  Abrir o teminal (git bash) no projeto "vplayer"
- [x]  Rodar o comando "npm install" no terminal;
- [x]  Rodar o comando "npm run dev" no terminal;

- [Como clonar um projeto no Github?](https://docs.github.com/pt/repositories/creating-and-managing-repositories/cloning-a-repository)
- [Node.js é um pré-requisito para rodar uma aplicação vue.js.](https://vuejs.org/guide/quick-start.html#creating-a-vue-application)
- [O que é o npm?](https://www.hostinger.com.br/tutoriais/o-que-e-npm)
- [O que é o packege.json](https://gabrieluizramos.com.br/entendendo-o-package-json)
- [O que é o git bash?](https://medium.com/@andradegabriela20/o-que-%C3%A9-git-git-bash-e-comandos-b%C3%A1sicos-94a53de6d376)

* Sinta-se a vontade para dar uma olhada no código, "tentar" entender o que já tem, tatear o código.

**Comment by pvmello** [comment]
Finalizei a primeira task
