### ISSUE TITLE
Melhorar VslSection.vue

### ISSUE THREAD

**Issue by daniel-francelino** [daniel-soaress/vplayer#4]
<details open><summary>Descrição</summary>

**O que?** 

- [x]  Criar a reponsividade do componente  para 'mobile' e ' tablet';

**Para que?** 

- Para que futuramente em múltiplas telas não ter problema de layout;

</details>

<details open><summary>Regras</summary>

- **R1.** Utilizar classes do "Tailwind" para aplicar responsividade do componente.;

- **R2.** É necessário reduzir o tamanhos de Fontes, Botões e Espaçamentos dependendo do tamanho:
 https://tailwindcss.com/docs/responsive-design

</details>

**Comment by daniel-francelino** [comment]
![Image](https://github.com/daniel-soaress/vplayer/assets/27651005/40ccb1f0-a804-4f0a-a672-d978f4b81268)

**Comment by pvmello** [comment]
I've made changes on the project and it seems to be fine to run on phones. On bigger consoles it seems a bit off. I'm not sure what I did wrong.
